version: '3.8'

services:
  app:
    build:
      context: .
      args:
        VITE_RECAPTCHA_SITE_KEY: ${VITE_RECAPTCHA_SITE_KEY}
        VITE_BASE_URL: ${VITE_BASE_URL:-/}
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
